
const products=[
{id:1,name:"مولتی ویتامین روزانه",category:"ویتامین و مکمل",price:289000,old:325000,stock:18,rating:4.8,img:"images/product_01.png",badge:"پرفروش",desc:"ترکیبی متعادل از ویتامین‌ها و مواد معدنی برای حمایت از سلامت عمومی بدن."},
{id:2,name:"ویتامین C 1000",category:"ویتامین و مکمل",price:198000,old:225000,stock:24,rating:4.9,img:"images/product_02.png",badge:"محبوب",desc:"مکمل ویتامین C برای حمایت از عملکرد طبیعی سیستم ایمنی و آنتی‌اکسیدان بدن."},
{id:3,name:"ویتامین D3",category:"ویتامین و مکمل",price:165000,old:190000,stock:32,rating:4.7,img:"images/product_03.png",badge:"تخفیف",desc:"مکمل ویتامین D3؛ مقدار مصرف را مطابق برچسب محصول یا توصیه پزشک و داروساز رعایت کنید."},
{id:4,name:"مراقبت پوست و مو",category:"پوست و مو",price:349000,old:399000,stock:11,rating:4.6,img:"images/product_04.png",badge:"جدید",desc:"محصول مراقبت پوستی با فرمول ملایم برای روتین روزانه."},
{id:5,name:"محصول مراقبت بدن",category:"بهداشت شخصی",price:219000,old:245000,stock:20,rating:4.5,img:"images/product_05.png",badge:"ویژه",desc:"انتخابی کاربردی برای مراقبت روزانه و بهداشت شخصی."},
{id:6,name:"مکمل انرژی و سلامت",category:"مکمل‌ها",price:299000,old:340000,stock:15,rating:4.7,img:"images/product_06.png",badge:"پرفروش",desc:"مکمل عمومی برای تکمیل رژیم غذایی؛ پیش از مصرف ترکیبات را بررسی کنید."},
{id:7,name:"محصول سلامت خانواده",category:"سلامت خانواده",price:420000,old:465000,stock:8,rating:4.8,img:"images/product_07_large.png",badge:"ویژه",desc:"محصولی کاربردی برای سبد سلامت خانواده."},
{id:8,name:"لوازم سلامت",category:"تجهیزات پزشکی",price:560000,old:620000,stock:7,rating:4.6,img:"images/products_1.png",badge:"پیشنهاد",desc:"تجهیزات و لوازم سلامت با تمرکز بر کاربرد و سهولت استفاده."}
];
const fmt=n=>document.documentElement.lang==="en"?new Intl.NumberFormat("en-US").format(n)+" IRR":new Intl.NumberFormat("fa-IR").format(n)+" تومان";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function cart(){return JSON.parse(localStorage.getItem("novin_cart")||"[]")}
function saveCart(c){localStorage.setItem("novin_cart",JSON.stringify(c));updateCount()}
function updateCount(){let n=cart().reduce((a,x)=>a+x.qty,0);$$(".cart-count").forEach(e=>e.textContent=n)}
function toast(t){let e=$("#toast");if(!e)return;e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500)}
function addToCart(id){let p=products.find(x=>x.id==id);if(!p)return;let c=cart(),x=c.find(x=>x.id==id);x?x.qty++:c.push({id,qty:1});saveCart(c);toast("محصول به سبد خرید اضافه شد")}
function wishlist(){try{const v=JSON.parse(localStorage.getItem('novin_wishlist')||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function toggleWishlist(id){id=Number(id);const set=new Set(wishlist());set.has(id)?set.delete(id):set.add(id);localStorage.setItem('novin_wishlist',JSON.stringify([...set]));syncWishlist();toast(document.documentElement.lang==='en'?(set.has(id)?'Saved to wishlist':'Removed from wishlist'):(set.has(id)?'به علاقه‌مندی‌ها اضافه شد':'از علاقه‌مندی‌ها حذف شد'))}
function syncWishlist(){const ids=new Set(wishlist());document.querySelectorAll('[data-wish]').forEach(b=>{const saved=ids.has(Number(b.dataset.wish));b.classList.toggle('active',saved);b.textContent=saved?'♥':'♡';b.setAttribute('aria-pressed',String(saved));b.setAttribute('aria-label',document.documentElement.lang==='en'?(saved?'Remove from wishlist':'Add to wishlist'):(saved?'حذف از علاقه‌مندی‌ها':'افزودن به علاقه‌مندی‌ها'))})}
function renderProducts(target=".product-grid",list=products){let el=$(target);if(!el)return;el.innerHTML=list.map(p=>`<article class="product"><div class="product-media"><button class="wish" aria-label="افزودن به علاقه‌مندی" data-wish="${p.id}">♡</button><span class="badge">${p.badge}</span><a href="shop-single.html?id=${p.id}"><img src="${p.img}" alt="${p.name}" loading="lazy"></a></div><div class="product-body"><div class="rating">★★★★★ <span>${p.rating}</span></div><h3><a href="shop-single.html?id=${p.id}">${p.name}</a></h3><small class="muted">${p.category}</small><div class="price"><div><strong>${fmt(p.price)}</strong><br><del class="muted" style="font-size:11px">${fmt(p.old)}</del></div><button class="mini-add" data-add="${p.id}" aria-label="افزودن به سبد">+</button></div></div></article>`).join("");syncWishlist()}
function bindProductButtons(){ $$(".product-grid").forEach(g=>{g.addEventListener("click",e=>{let a=e.target.closest("[data-add]"),w=e.target.closest("[data-wish]");if(a)addToCart(a.dataset.add);if(w)toggleWishlist(w.dataset.wish)})})}
function setupSearch(){let input=$("#globalSearch"),box=$("#searchResults");if(!input||!box)return;input.addEventListener("input",()=>{let q=input.value.trim().toLowerCase();let r=products.filter(p=>(p.name+p.category).toLowerCase().includes(q)).slice(0,6);box.innerHTML=r.map(p=>`<a class="result" href="shop-single.html?id=${p.id}"><span>${p.name}</span><b>${fmt(p.price)}</b></a>`).join("");box.classList.toggle("show",q.length>0&&r.length>0)});document.addEventListener("click",e=>{if(!e.target.closest(".search-wrap"))box.classList.remove("show")})}
function initShop(){
 const grid=$(".product-grid"),search=$("#shopSearch"),sort=$("#sortProducts"),cat=$("#categoryFilter");if(!grid)return;
 const max=$("#priceLimit"),stock=$("#inStockOnly"),reset=$("#resetFilters"),count=$("#shopResultCount"),empty=$("#shopEmpty");
 const apply=()=>{
  const q=(search?.value||"").trim().toLocaleLowerCase(),c=cat?.value||"",limit=max?.value?Number(max.value):Infinity;
  let arr=products.filter(p=>{const en=window.novinProductEn?.[p.id]||[];return (p.name+" "+p.category+" "+en.join(" ")).toLocaleLowerCase().includes(q)&&(!c||p.category===c)&&p.price<=limit&&(!stock?.checked||p.stock>0)});
  if(sort?.value==="low")arr.sort((a,b)=>a.price-b.price);if(sort?.value==="high")arr.sort((a,b)=>b.price-a.price);if(sort?.value==="rating")arr.sort((a,b)=>b.rating-a.rating);
  renderProducts(".product-grid",arr);bindProductButtons();const en=document.documentElement.lang==="en";
  if(count)count.textContent=en?`${arr.length} products found`:`${arr.length} محصول یافت شد`;
  if(empty){empty.hidden=arr.length>0;empty.textContent=en?"No products match your filters. Try clearing them.":"محصولی مطابق فیلترها پیدا نشد. فیلترها را پاک کنید."}
  window.novinTranslate?.();
 };
 [search,sort,cat,max,stock].forEach(x=>x?.addEventListener("input",apply));
 reset?.addEventListener("click",()=>{if(search)search.value="";if(sort)sort.value="";if(cat)cat.value="";if(max)max.value="";if(stock)stock.checked=true;apply()});
 if(search){const q0=new URLSearchParams(location.search).get("q");if(q0)search.value=q0}apply();document.addEventListener("novin:languagechange",apply);
}
function initProduct(){let id=new URLSearchParams(location.search).get("id")||1,p=products.find(x=>x.id==id)||products[0],e=$("#productDetail");if(!e)return;e.innerHTML=`<div class="detail-img"><img src="${p.img}" alt="${p.name}"></div><div><span class="tag">${p.badge}</span><h1>${p.name}</h1><div class="rating">★★★★★ ${p.rating}</div><p class="muted">${p.desc}</p><div class="notice">این صفحه برای نمایش اطلاعات محصول است. داروهای نسخه‌ای فقط پس از بررسی نسخه و شرایط بیمار باید تهیه و مصرف شوند.</div><div style="margin:22px 0"><strong style="font-size:26px;color:var(--primary)">${fmt(p.price)}</strong> <del class="muted">${fmt(p.old)}</del></div><div class="hero-actions"><button class="btn btn-primary" data-add="${p.id}">افزودن به سبد</button><a class="btn btn-outline" href="prescription.html">ارسال نسخه</a></div><div class="muted">موجودی نمایشی: ${p.stock} عدد · ارسال سریع در محدوده فعال</div></div>`;e.addEventListener("click",x=>{let b=x.target.closest("[data-add]");if(b)addToCart(b.dataset.add)})}
function initCart(){let wrap=$("#cartContent"),items=cart();if(!wrap)return;if(!items.length){wrap.innerHTML=`<div class="info-card" style="text-align:center;padding:50px"><h2>سبد خرید شما خالی است</h2><p class="muted">محصولات مورد نیازتان را از فروشگاه انتخاب کنید.</p><a class="btn btn-primary" href="shop.html">مشاهده محصولات</a></div>`;return}let rows=items.map(x=>{let p=products.find(y=>y.id==x.id);return `<tr><td data-label="محصول"><div class="cart-product"><img src="${p.img}" alt="${p.name}"><div><strong>${p.name}</strong><small class="muted" style="display:block">${p.category}</small></div></div></td><td data-label="قیمت">${fmt(p.price)}</td><td data-label="تعداد"><div class="qty"><button data-minus="${p.id}">−</button><input value="${x.qty}" readonly><button data-plus="${p.id}">+</button></div></td><td data-label="جمع"><strong>${fmt(p.price*x.qty)}</strong></td><td><button class="btn btn-outline" style="padding:7px 10px" data-remove="${p.id}">حذف</button></td></tr>`}).join("");let total=items.reduce((a,x)=>a+(products.find(p=>p.id==x.id)?.price||0)*x.qty,0);wrap.innerHTML=`<div><table class="cart-table"><thead><tr><th>محصول</th><th>قیمت</th><th>تعداد</th><th>جمع</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><aside class="summary"><h3>خلاصه سفارش</h3><div class="sum-row"><span>جمع محصولات</span><b>${fmt(total)}</b></div><div class="sum-row"><span>ارسال</span><b>${total>=1000000?"رایگان":fmt(65000)}</b></div><div class="sum-row sum-total"><span>قابل پرداخت</span><b>${fmt(total+(total>=1000000?0:65000))}</b></div><a href="checkout.html" class="btn btn-primary" style="width:100%;margin-top:15px">ادامه و ثبت سفارش</a></aside>`;wrap.addEventListener("click",e=>{let c=cart(),id=+(e.target.dataset.plus||e.target.dataset.minus||e.target.dataset.remove);if(!id)return;let x=c.find(y=>y.id===id);if(e.target.dataset.plus)x.qty++;if(e.target.dataset.minus)x.qty=Math.max(0,x.qty-1);if(e.target.dataset.remove)x.qty=0;c=c.filter(y=>y.qty>0);saveCart(c);initCart()})}
function initCheckout(){let form=$("#checkoutForm");if(!form)return;let total=cart().reduce((a,x)=>a+(products.find(p=>p.id==x.id)?.price||0)*x.qty,0);$("#checkoutTotal")&&( $("#checkoutTotal").textContent=fmt(total+(total>=1000000?0:65000)) );form.addEventListener("submit",e=>{e.preventDefault();if(!cart().length){toast("سبد خرید خالی است");return}localStorage.removeItem("novin_cart");location.href="thankyou.html"})}
function initFAQ(){ $$(".faq-q").forEach(q=>q.addEventListener("click",()=>q.parentElement.classList.toggle("open"))) }
function initPrescription(){let f=$("#rxForm"),input=$("#rxFile"),preview=$("#fileName");if(!f)return;input?.addEventListener("change",()=>preview.textContent=input.files[0]?`فایل انتخاب شد: ${input.files[0].name}`:"فایلی انتخاب نشده");f.addEventListener("submit",e=>{e.preventDefault();toast("درخواست نسخه به‌صورت نمایشی ثبت شد؛ برای اتصال واقعی به سرور نیاز به API دارید.");f.reset()})}
function initContact(){let f=$("#contactForm");f?.addEventListener("submit",e=>{e.preventDefault();toast("پیام شما در نسخه نمایشی ثبت شد.");f.reset()})}
function initNewsletter(){let f=$("#newsletter");f?.addEventListener("submit",e=>{e.preventDefault();toast("عضویت شما در خبرنامه ثبت شد.");f.reset()})}
function initTheme(){let key="novin_theme",b=$("#themeToggle");if(localStorage.getItem(key)==="dark")document.body.classList.add("dark");b?.addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem(key,document.body.classList.contains("dark")?"dark":"light")})}
function initMobile(){let b=$("#menuToggle"),m=$("#mobileMenu");if(!b||!m)return;b.setAttribute("aria-expanded","false");b.addEventListener("click",()=>{const show=!m.classList.contains("show");m.classList.toggle("show",show);m.style.display=show?"block":"none";b.setAttribute("aria-expanded",String(show))});m.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{m.classList.remove("show");m.style.display="none";b.setAttribute("aria-expanded","false")}))}
function initChat(){let c=$("#chat"),fab=$("#chatFab"),form=$("#chatForm"),input=$("#chatInput"),body=$("#chatBody");if(!c)return;fab.onclick=()=>c.classList.toggle("open");const reply=q=>{q=q.toLowerCase();if(document.documentElement.lang==="en"){if(/prescription|upload|rx/.test(q))return "Use the prescription page to submit a request. Do not share sensitive medical details in chat.";if(/order|shipping|delivery/.test(q))return "Orders and delivery are demonstrations in this frontend version.";if(/vitamin|medicine|dose|supplement/.test(q))return "I can help you browse products, but a pharmacist or doctor should advise on medication and dosage.";return "Welcome to Novin Daroo! Ask about products, prescriptions, or orders. I am a demo assistant, not a medical professional.";}if(q.includes("ساعت")||q.includes("باز"))return"ساعت کاری نمایشی: شنبه تا پنجشنبه ۸ تا ۲۲ و جمعه ۹ تا ۱۸ است.";if(q.includes("نسخه"))return"برای ارسال نسخه از صفحه «ارسال نسخه» استفاده کنید. لطفاً اطلاعات حساس غیرضروری را در چت ارسال نکنید.";if(q.includes("ویتامین")||q.includes("مکمل"))return"می‌توانم در پیدا کردن محصولات کمک کنم، اما درباره شروع/قطع دارو یا دوز مصرفی باید با داروساز یا پزشک مشورت کنید.";if(q.includes("ارسال")||q.includes("تحویل"))return"در این نسخه، ارسال سریع و امکان تحویل حضوری به‌صورت نمایشی در نظر گرفته شده است.";return"سلام! من دستیار هوشمند نوین‌دارو هستم. درباره محصولات، ارسال نسخه، سفارش و خدمات سایت سؤال کنید. پاسخ‌های من جایگزین نظر پزشک یا داروساز نیستند."};form?.addEventListener("submit",e=>{e.preventDefault();let q=input.value.trim();if(!q)return;const user=document.createElement("div");user.className="msg user";user.textContent=q;const bot=document.createElement("div");bot.className="msg bot";bot.textContent=reply(q);body.append(user,bot);input.value="";body.scrollTop=body.scrollHeight})}
function initWishlistPage(){const host=document.getElementById('wishlistGrid');if(!host)return;const ids=new Set(wishlist());renderProducts('#wishlistGrid',products.filter(p=>ids.has(p.id)));if(!ids.size)host.innerHTML='<div class="info-card" style="padding:32px">'+(document.documentElement.lang==='en'?'Your wishlist is empty. Browse products to save your favorites.':'لیست علاقه‌مندی‌های شما خالی است.')+' <a href="shop.html">'+(document.documentElement.lang==='en'?'Browse shop':'مشاهده فروشگاه')+'</a></div>';host.addEventListener('click',e=>{const a=e.target.closest('[data-add]'),w=e.target.closest('[data-wish]');if(a)addToCart(a.dataset.add);if(w){toggleWishlist(w.dataset.wish);initWishlistPage()}})}
function initGlobal(){updateCount();setupSearch();initTheme();initMobile();initFAQ();initPrescription();initContact();initNewsletter();initChat();document.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",()=>addToCart(b.dataset.add)))}
document.addEventListener("DOMContentLoaded",()=>{initGlobal();renderProducts(".product-grid");bindProductButtons();initShop();initProduct();initCart();initCheckout();initWishlistPage();document.addEventListener("novin:languagechange",()=>{renderProducts(".product-grid");initProduct();initWishlistPage();syncWishlist()});});
