(()=>{
'use strict';
const translations={"خانه": "Home", "فروشگاه": "Shop", "خدمات سلامت": "Health Services", "ارسال نسخه": "Submit Prescription", "مجله سلامت": "Health Journal", "درباره ما": "About Us", "تماس": "Contact", "تماس با ما": "Contact Us", "سوالات متداول": "FAQ", "سبد خرید": "Cart", "جستجوی محصولات": "Search Products", "تغییر تم": "Toggle Theme", "منوی موبایل": "Mobile Menu", "پرش به محتوای اصلی": "Skip to main content", "نوین‌دارو": "Novin Daroo", "سلامت، ساده و مطمئن": "Health, made simple", "پشتیبانی داروساز · پاسخ‌گویی سریع": "Pharmacy support · Quick response", "محصولات": "Products", "محصول": "Product", "قیمت": "Price", "تعداد": "Quantity", "جمع": "Total", "حذف": "Remove", "رایگان": "Free", "ارسال": "Shipping", "قابل پرداخت": "Amount Due", "جمع محصولات": "Subtotal", "خلاصه سفارش": "Order Summary", "ادامه و ثبت سفارش": "Proceed to Checkout", "افزودن به سبد خرید": "Add to Cart", "افزودن به علاقه‌مندی": "Add to Wishlist", "ویتامین و مکمل": "Vitamins & Supplements", "پوست و مو": "Skin & Hair", "بهداشت شخصی": "Personal Care", "مکمل‌ها": "Supplements", "سلامت خانواده": "Family Health", "تجهیزات پزشکی": "Medical Equipment", "پرفروش": "Bestseller", "محبوب": "Popular", "تخفیف": "Sale", "جدید": "New", "ویژه": "Special", "پیشنهاد": "Recommended", "مولتی ویتامین روزانه": "Daily Multivitamin", "ویتامین C 1000": "Vitamin C 1000", "ویتامین D3": "Vitamin D3", "مراقبت پوست و مو": "Skin & Hair Care", "محصول مراقبت بدن": "Body Care Product", "مکمل انرژی و سلامت": "Energy & Wellness Supplement", "محصول سلامت خانواده": "Family Wellness Product", "لوازم سلامت": "Health Equipment", "نام": "Name", "ایمیل": "Email", "شماره تماس": "Phone Number", "آدرس": "Address", "پیام": "Message", "ثبت سفارش": "Place Order", "ادامه مطلب": "Read More", "مشاهده محصولات": "Browse Products", "مشاهده همه": "View All", "جستجو": "Search", "دسته‌بندی": "Category", "مرتب‌سازی": "Sort By", "درباره نوین‌دارو": "About Novin Daroo", "پرسش‌های متداول": "Frequently Asked Questions", "ورود": "Sign In", "ثبت نام": "Sign Up", "بازگشت": "Back", "صفحه اصلی": "Home", "خدمات": "Services", "نام و نام خانوادگی": "Full Name", "توضیحات": "Description", "آپلود نسخه": "Upload Prescription", "ارسال درخواست": "Send Request", "ارسال پیام": "Send Message", "ثبت": "Submit", "کد پستی": "Postal Code", "شهر": "City", "استان": "Province", "پرداخت": "Payment", "اطلاعات تماس": "Contact Information", "خبرنامه": "Newsletter", "عضویت": "Subscribe", "مطالب مرتبط": "Related Articles", "بیشتر بخوانید": "Read More", "تخفیف ویژه": "Special Offer"};
Object.assign(translations,{"داروخانه دیجیتال نسل جدید": "A new generation of digital pharmacy", "سلامت شما،": "Your health,", "اولویت ماست": "our priority", "محصولات سلامت، مکمل‌ها و خدمات داروخانه را با تجربه‌ای سریع، شفاف و آرامش‌بخش پیدا کنید.": "Discover wellness products, supplements and pharmacy services with clarity and confidence.", "شروع خرید": "Shop now", "نام محصول، ویتامین یا دسته‌بندی را جستجو کنید...": "Search products, vitamins or categories...", "دسته‌بندی‌های محبوب": "Popular categories", "مسیر کوتاه‌تر برای رسیدن به محصول مورد نیاز": "Find what you need faster", "همه محصولات ←": "All products →", "دارو و درمان": "Medicine & Care", "پرداخت امن": "Secure checkout", "آماده اتصال به درگاه امن": "Ready for secure payment integration", "خدمات سلامت": "Health services", "فراتر از یک فروشگاه اینترنتی": "More than an online store", "همه خدمات": "All services", "ثبت و پیگیری نسخه": "Prescription requests", "ارسال آنلاین نسخه و دریافت راهنمایی برای ادامه فرایند.": "Submit a prescription request and learn the next steps.", "تحویل و دریافت": "Delivery & pickup", "انتخاب روش تحویل و نمایش خلاصه سفارش به‌صورت شفاف.": "Choose a delivery option and review your order.", "دستیار هوشمند": "Virtual assistant", "راهنمایی درباره امکانات سایت و یافتن محصولات با جستجوی ساده.": "Find products and explore site features with guided assistance.", "شروع ←": "Get started →", "جزئیات ←": "Details →", "گفت‌وگو ←": "Chat →", "نظر کاربران": "Customer stories", "نمونه‌ای از بازخوردهای نمایشی": "Illustrative feedback for this demo", "مجله سلامت در ایمیل شما": "Wellness insights in your inbox", "مقالات عمومی سلامت، معرفی محصولات و نکات کاربردی.": "General wellness articles, product news and practical tips.", "ایمیل شما": "Your email", "دسترسی سریع": "Quick links", "راهنما": "Help", "ارتباط": "Connect", "حریم خصوصی": "Privacy policy", "پاسخ‌گوی محصولات و راهنمای سایت": "Product and website guidance · Demo", "دستیار نوین‌دارو": "Novin Daroo assistant", "سلام! درباره محصولات، ارسال نسخه یا خدمات سایت چه کمکی می‌خواهید؟": "Hi! Ask me about products, prescriptions or using the site.", "مثلاً: ارسال نسخه چطور است؟": "e.g. How do prescriptions work?", "باز کردن دستیار": "Open assistant", "تهران، خیابان نمونه، پلاک ۱۲": "Tehran, sample street (demo address)", "یک رابط کاربری مدرن برای فروشگاه و خدمات دیجیتال داروخانه؛ با تمرکز بر اعتماد، دسترسی و تجربه کاربری.": "A modern demo storefront for pharmacy services, designed for clarity and accessibility.", "© ۱۴۰۵ نوین‌دارو — نسخه نمایشی فرانت‌اند": "© 2026 Novin Daroo — Frontend demo", "طراحی شده با رویکرد دسترسی‌پذیر و سریع": "Built for accessibility and speed", "ارسال رایگان برای سفارش‌های بالای ۱ میلیون تومان ·": "Free shipping offer (demo) ·", "منوی اصلی": "Main navigation"});
Object.assign(translations,{"نام محصول...":"Product name...","همه دسته‌ها":"All categories","ارزان‌ترین":"Price: low to high","گران‌ترین":"Price: high to low","بیشترین امتیاز":"Top rated","محصولات منتخب نوین‌دارو":"Curated wellness products","یادآوری":"Please note","اطلاعات این فروشگاه نمایشی است و اتصال واقعی به موجودی و داروخانه نیاز به بک‌اند دارد.":"This is a demonstration storefront; live stock and pharmacy integration require a backend."});
const productEn={1:['Daily Multivitamin','Balanced vitamins and minerals for everyday wellbeing.'],2:['Vitamin C 1000','Vitamin C supplement; follow product instructions.'],3:['Vitamin D3','Vitamin D3 supplement; consult a clinician about dosage.'],4:['Skin & Hair Care','Gentle daily skincare product.'],5:['Body Care Product','Everyday personal hygiene and body care.'],6:['Energy & Wellness Supplement','General dietary supplement; check ingredients before use.'],7:['Family Wellness Product','A practical family wellness product.'],8:['Health Equipment','Health supplies designed for ease of use.']};
const initial=new WeakMap();
function translateText(s){const trim=s.trim();if(!trim)return s;const found=translations[trim];return found?s.replace(trim,found):s;}
function apply(){const lang=localStorage.getItem('novin_lang')==='fa'?'fa':'en';document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';document.body.classList.toggle('lang-en',lang==='en');document.title=lang==='en'?'Novin Daroo | Online Pharmacy & Wellness':'نوین‌دارو | داروخانه آنلاین و محصولات سلامت';document.querySelectorAll('[data-lang-switch]').forEach(b=>{b.textContent=lang==='en'?'فارسی':'English';b.setAttribute('aria-label',lang==='en'?'Switch to Persian':'تغییر به انگلیسی')});
const walk=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walk.nextNode()){if(n.parentElement?.closest('script,style,textarea,[data-lang-switch]'))continue;if(!initial.has(n))initial.set(n,n.nodeValue);let original=initial.get(n);n.nodeValue=lang==='en'?translateText(original):original;}
document.querySelectorAll('[placeholder],[aria-label],[title]').forEach(el=>{for(const attr of ['placeholder','aria-label','title']){if(!el.hasAttribute(attr))continue;const key='data-original-'+attr;if(!el.hasAttribute(key))el.setAttribute(key,el.getAttribute(attr));const value=el.getAttribute(key);el.setAttribute(attr,lang==='en'?translateText(value):value)}});
document.querySelectorAll('.product').forEach(el=>{const id=+(el.querySelector('[data-add]')?.getAttribute('data-add')||new URL(el.querySelector('a[href*="id="]')?.href||location.href).searchParams.get('id'));if(lang==='en'&&productEn[id]){const h=el.querySelector('h3,h4,.product-title');if(h)h.textContent=productEn[id][0]}});
}
function inject(){document.querySelectorAll('.actions').forEach(a=>{if(a.querySelector('[data-lang-switch]'))return;const b=document.createElement('button');b.type='button';b.className='language-toggle';b.setAttribute('data-lang-switch','');b.addEventListener('click',()=>{localStorage.setItem('novin_lang',document.documentElement.lang==='en'?'fa':'en');apply();document.dispatchEvent(new Event("novin:languagechange"))});a.prepend(b)});apply()}
window.novinTranslate=apply;
window.novinProductEn=productEn;
document.addEventListener('DOMContentLoaded',()=>{inject();setTimeout(apply,0)});const observer=new MutationObserver(()=>{clearTimeout(window.__novinTranslateTimer);window.__novinTranslateTimer=setTimeout(apply,80)});document.addEventListener('DOMContentLoaded',()=>observer.observe(document.querySelector('main')||document.body,{childList:true,subtree:true}));
})();