/* Stage 8: bilingual accessible enhancements, demo-safe product experience */
(()=>{'use strict';
const lang=()=>document.documentElement.lang==='fa'?'fa':'en';
const copy={en:{top:'Explore our wellness collection',shop:'Explore products',assistant:'Demo assistant — not medical advice',search:'Search products',clear:'Clear search',back:'Back to top',note:'For medicine questions, speak to a licensed pharmacist. Never enter private health data in this demo.',skip:'Skip to main content'},fa:{top:'مجموعه محصولات سلامت را ببینید',shop:'مشاهده محصولات',assistant:'دستیار نمایشی — نه مشاوره پزشکی',search:'جستجوی محصولات',clear:'پاک‌کردن جستجو',back:'بازگشت به بالا',note:'برای پرسش‌های دارویی با داروساز دارای مجوز مشورت کنید. اطلاعات پزشکی خصوصی را در این نسخه وارد نکنید.',skip:'پرش به محتوای اصلی'}};
function setup(){if(!document.getElementById('stage8Skip')){const a=document.createElement('a');a.id='stage8Skip';a.className='stage8-skip';a.href='#mainContent';document.body.prepend(a);const main=document.querySelector('main');if(main&&!main.id)main.id='mainContent';}
if(!document.getElementById('stage8Top')){const b=document.createElement('button');b.id='stage8Top';b.type='button';b.className='stage8-top';b.textContent='↑';b.addEventListener('click',()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));document.body.append(b);window.addEventListener('scroll',()=>b.classList.toggle('visible',scrollY>450),{passive:true});}
const chat=document.querySelector('#chat');if(chat&&!chat.querySelector('.stage8-chat-note')){const p=document.createElement('p');p.className='stage8-chat-note';chat.querySelector('#chatBody')?.before(p);}
const search=document.querySelector('#globalSearch');if(search&&!document.getElementById('stage8Clear')){const btn=document.createElement('button');btn.type='button';btn.id='stage8Clear';btn.className='stage8-clear';btn.textContent='×';btn.addEventListener('click',()=>{search.value='';search.dispatchEvent(new Event('input',{bubbles:true}));search.focus();});search.parentElement.append(btn);}
render();}
function render(){const t=copy[lang()];const skip=document.getElementById('stage8Skip');if(skip)skip.textContent=t.skip;const top=document.getElementById('stage8Top');if(top)top.setAttribute('aria-label',t.back);const note=document.querySelector('.stage8-chat-note');if(note)note.textContent=t.note;const clear=document.getElementById('stage8Clear');if(clear)clear.setAttribute('aria-label',t.clear);}
document.addEventListener('DOMContentLoaded',setup);document.addEventListener('novin:languagechange',()=>requestAnimationFrame(render));
})();
